name: Code Quality

on:
    push:
    pull_request:
        branches: [ 1.x ]
    workflow_dispatch:

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        name: Coding Standards
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1' # Let's run the tool on the lowest supported php version to ensure it passes
                    coverage: none
                    tools: php-cs-fixer, cs2pr

            -   name: PHP Coding Standards Fixer
                run: php-cs-fixer fix --dry-run --format checkstyle | cs2pr

    psalm:
        runs-on: ubuntu-latest
        name: Static Analysis (Psalm)
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: none
                    tools: psalm

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'

            -   name: Run Psalm
                run: psalm --long-progress --no-diff --output-format=github

    phpstan:
        runs-on: ubuntu-latest
        name: Static Analysis (PHPStan)
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: none
                    tools: phpstan

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'

            -   name: Run PHPStan
                run: phpstan analyse --no-progress
