name: Tests

on:
    push:
    pull_request:
        branches: [ 1.x ]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpunit:
        # runs-on: ubuntu-latest TODO change this when going public
        runs-on: [ self-hosted, k8s ]
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                symfony: [ '5.4', '6.4', '7.0', '7.1' ]
                dependencies: [ 'highest', 'lowest' ]
                exclude:
                    -   php: '8.1'
                        symfony: '7.0'
                    -   php: '8.1'
                        symfony: '7.1'
        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        name: PHP ${{ matrix.php }} & Symfony ${{ matrix.symfony }}${{ matrix.dependencies == 'lowest' && ' (lowest)' || '' }} Test
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                env:
                    runner: self-hosted # TODO remove this when going public
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex
                    extensions: sqlite # TODO remove this when going public
                    coverage: xdebug # TODO remove this when going public

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'
                    dependency-versions: ${{ matrix.dependencies }}

            -   name: Run Tests
                run: vendor/bin/phpunit --log-junit=junit.xml --coverage-text --coverage-clover=coverage.xml

            -   name: Publish Test Report
                uses: mikepenz/action-junit-report@v4
                if: always()
                with:
                    check_name: PHPUnit Execution Report
                    fail_on_failure: 'true'
                    require_tests: 'true'
                    report_paths: ./junit.xml

            -   name: Report Test Coverage
                if: ${{ github.event_name == 'pull_request' }}
                uses: slavcodev/coverage-monitor-action@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    coverage_path: coverage.xml
                    threshold_alert: 3
                    threshold_warning: 50
                    comment_mode: update
